# Generated by Django 4.2.11 on 2026-02-27 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rated_user', 'rating_user')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user', '-created_at'], name='rating_rated_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating_user'], name='rating_user_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user', 'rating'], name='rating_score_idx'),
        ),
    ]
