# Generated by Django 4.2.11 on 2026-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', '-created_at'], name='issue_status_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['priority', '-created_at'], name='issue_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assigned_to', 'status'], name='issue_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['apartment', '-created_at'], name='issue_apartment_idx'),
        ),
    ]
