# Generated by Django 4.2.11 on 2026-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['reputation'], name='profile_reputation_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['report_count'], name='profile_report_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['occupation'], name='profile_occupation_idx'),
        ),
    ]
