# Generated by Django 4.2.11 on 2026-02-27 09:09

import core_apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['building', 'floor', 'unit_number'], 'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.CharField(max_length=50, validators=[core_apps.common.validators.validate_no_html], verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='unit_number',
            field=models.CharField(max_length=10, unique=True, validators=[core_apps.common.validators.validate_no_html], verbose_name='Unit Number'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['building', 'floor'], name='apt_building_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['tenant'], name='apt_tenant_idx'),
        ),
    ]
