# Generated by Django 4.2.11 on 2026-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='post_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-upvotes', '-created_at'], name='post_popular_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='post_author_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['post', '-created_at'], name='reply_post_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['author', '-created_at'], name='reply_author_idx'),
        ),
    ]
